### PR TITLE
hardware: sprd: Fix "reference to 'ION_MM' is ambiguous"

### PR DESCRIPTION
**Pull request by Roker2**
Full log
https://gist.github.com/Roker2/e4a2ef952473e90b5e253e685071ed04

Change-Id: I6ef325a9548d576a1a80343bf5fb2aa6d70a9e57

### CODE REVIEW

**Comment by Roker2** [comment]
I checked, it help and ROM is worked.

**Comment by diepquynh** [comment]
Hmm I suppose the `SCX30G_V2` cflags got ignored. Please keep the commit in another repo instead, as a temporary solution

**Comment by Roker2** [comment]
Okay, I will push it to cm-13.0-temp in my repository, ok?

**Comment by diepquynh** [comment]
yes that's a nice approach

**Pull request closed without merging**
